import { BentoDash } from './DashboardTwo';

/**
 * SWISS — stark white, hairline 1px black borders, single forest-green accent,
 * no shadows, no radius. Helvetica. Editorial / archival vibe.
 * Same bento layout as /2 — only the paint changes.
 */
export function DashboardThree() {
  return <BentoDash theme={SWISS_THEME} />;
}

const SWISS_THEME = {
  name: 'swiss',
  font: '"Helvetica Neue", "Arial", system-ui, sans-serif',
  fontImport: null,
  appBg: '#ffffff',
  fg: '#0a0a0a',
  muted: '#6e6e6e',
  radius: 0,
  sidebarBg: '#ffffff',
  sidebarBorder: '1px solid #0a0a0a',
  headerBorder: '1px solid #0a0a0a',
  cardBg: '#ffffff',
  cardBorder: '1px solid #0a0a0a',
  cardShadow: 'none',
  navFg: '#6e6e6e',
  navIconBg: '#f4f4f4',
  navIconFg: '#6e6e6e',
  navActiveBg: '#0a0a0a',
  navActiveFg: '#ffffff',
  navActiveIconBg: '#0a0a0a',
  navActiveIconFg: '#ffffff',
  badgeBg: '#1a7a4a',
  badgeFg: '#ffffff',
  logoBg: '#0a0a0a',
  logoFg: '#ffffff',
  profileBg: '#f4f4f4',
  av1: '#d4e8dc',
  av1Fg: '#0a3a22',
  av2: '#f4f4f4',
  av2Fg: '#0a0a0a',
  primaryBg: '#0a0a0a',
  primaryFg: '#ffffff',
  chipBg: '#ffffff',
  chipBorder: '1px solid #0a0a0a',
  actionBg: '#1a7a4a',
  actionFg: '#ffffff',
  actionLabel: 'rgba(255,255,255,.7)',
  actionAccent: '#ffffff',
  actionBorder: 'none',
  actionBtnBg: '#ffffff',
  actionBtnFg: '#0a0a0a',
  actionGhostBorder: 'rgba(255,255,255,.4)',
  actionRowBg: 'rgba(255,255,255,.12)',
  actionRowFg: '#ffffff',
  actionRowMuted: 'rgba(255,255,255,.55)',
  actionRowBorder: '1px solid rgba(255,255,255,.2)',
  thumbBg: '#f4f4f4',
  thumbBorder: '1px solid #0a0a0a',
  good: '#1a7a4a',
  barTrack: '#f4f4f4',
  barFill: '#1a7a4a',
  numBg: '#f4f4f4',
  numFg: '#0a0a0a',
  linkFg: '#1a7a4a',
};
